### ISSUE TITLE
weird characters in output

### ISSUE THREAD

**Issue by 0-wiz-0** [Sude-/lgogdownloader#112]
When fetching overfall, I see:
````
...
patch_overfall_03222017_(10837)_to_3222017(a)_(12536).exe
        MD5:    49d0c5580c2b1eb3ef3f0f8be03bc1ab
        Chunks: 17
        Size:   171001240 bytes

Chunk 16 (3229080 bytes): OK

Repairing file ./overfall/overfall_ost_mp3.zip
XML: Using local file
XML: Valid XML
XML: Parsing finished

overfall_ost_mp3.zip
        MD5:    �
�
        Chunks: 8
        Size:   75820731 bytes

Chunk 7 (2420411 bytes): OK

Checking for orphaned files 1 / 1
No orphaned files
```
`--list-details` on this game seems to be missing `size` for this file as well:
````
DLCs:
        gamename: overfall_soundtrack
        id: 67443
        name: soundtrack (MP3)
        path: /overfall_soundtrack/extras/overfall_ost_mp3.zip
        size:

````
