### ISSUE TITLE
Problem with Linux files for the_bards_tale_iv_directors_cut

### ISSUE THREAD

**Issue by 0-wiz-0** [Sude-/lgogdownloader#154]
The Linux files for the_bards_tale_iv_directors_cut are one big zip archive split into multiple files.
`lgogdownloader --list-details --language all --platform all` list them as:
````
gamename: the_bards_tale_iv_directors_cut
product id: 2110182857
title: The Bard's Tale IV: Director's Cut
icon: ...
installers: 
...
        id: en2installer2
        name: The Bard's Tale IV: Director's Cut
        path: /the_bards_tale_iv_directors_cut/The_Bards_Tale_IV_Directors_Cut_Update1.zip.001
        size: 3984588800
        updated: False
        language: English
... (up to 013, and)...
        id: en3installer2
        name: The Bard's Tale IV: Director's Cut
        path: /the_bards_tale_iv_directors_cut/the_bard_s_tale_iv_director_s_cut_4_20_1_153615_32362_linux.zip.001
        size: 4194304000
        updated: False
        language: English
...(up to 009)...
````
but lgogdownloader doesn't fetch those files, or at least I didn't find the magic incantation that does.
