### ISSUE TITLE
game specific settings, multiple languages not picked up

### ISSUE THREAD

**Issue by shakeyourbunny** [Sude-/lgogdownloader#75]
LGOGDownloader 2.26.9cf9a8f seems not to pick up the gamespecific language settings correctly, if there are multiple language set. It seems that the command line ( --language en,de [download english version if it exists, german only if no english version exists]) still overrides the game-specific settings (**"language": "de+en"** [download German AND English version]), if there is some kind of multi-language setting in the configuration file (a single language works).

Configuration:
.config/lgogdownloader/gamespecific/darkstone.conf

```
{
    "language": "de+en"
}
```

$ ls -R darkstone

```
darkstone:
cover_0.png  extras  folder.jpg  setup_darkstone_2.0.0.10.exe  

darkstone/extras:
darkstone_artworks.zip  darkstone_manual.zip      darkstone_wallpapers.zip
darkstone_avatars.zip   darkstone_soundtrack.zip
```

Output:
$ lgogdownloader --download --directory /storage/spielkrams/GOG --language en,de --no-unicode --platform win --no-duplicate-handling --limit-rate 3900 --save-serials --use-cache --game darkstone

yields (files are downloaded, but not the German installer):

```
darkstone - Language: 3, Platform: 1, DLC: true
Downloading cover /storage/spielkrams/GOG/darkstone/cover_0.png
  0% [                          ] 1.17/1.17MB @ 0.00kB/s ETA: 0s
Downloading: Windows Installer, English
/storage/spielkrams/GOG/darkstone/setup_darkstone_2.0.0.10.exe
100% [==========================] 430.60/430.60MB @ 0.00kB/s ETA: 0s
Downloading: manual
/storage/spielkrams/GOG/darkstone/extras/darkstone_manual.zip
100% [==========================] 4.87/4.87MB @ 0.00kB/s ETA: 0s
Downloading: wallpapers
/storage/spielkrams/GOG/darkstone/extras/darkstone_wallpapers.zip
100% [==========================] 17.19/17.19MB @ 0.00kB/s ETA: 0s
Downloading: soundtrack
/storage/spielkrams/GOG/darkstone/extras/darkstone_soundtrack.zip
100% [==========================] 39.13/39.13MB @ 0.00kB/s ETA: 0s
Downloading: avatars
/storage/spielkrams/GOG/darkstone/extras/darkstone_avatars.zip
100% [==========================] 0.18/0.18MB @ 0.00kB/s ETA: 0s
Downloading: artworks
/storage/spielkrams/GOG/darkstone/extras/darkstone_artworks.zip
100% [==========================] 6.13/6.13MB @ 0.00kB/s ETA: 0s
```

./lgogdownloader --list-details --game  darkstone

```
darkstone - Language: 3, Platform: 5, DLC: true
gamename: darkstone
title: Darkstone
icon: http://static.gog.com/upload/images/2012/04/198a79dc9408f88a2d4e727d031afbfb4daac30e.jpg
installers:
        id: en1installer0
        name: Windows Installer, English
        path: /darkstone/pc/setup_darkstone_2.0.0.10.exe
        size: 430.7
        updated: False
        language: English

        id: de1installer1
        name: Windows Installer, German
        path: /darkstone/pc/setup_darkstone_german_2.1.0.12.exe
        size: 505.0
        updated: False
        language: German

extras:
        id: 14423
        name: manual
        path: /darkstone/extras/darkstone_manual.zip
        size:

        id: 14433
        name: wallpapers
        path: /darkstone/extras/darkstone_wallpapers.zip
        size:

        id: 14443
        name: soundtrack
        path: /darkstone/extras/darkstone_soundtrack.zip
        size:

        id: 14413
        name: avatars
        path: /darkstone/extras/darkstone_avatars.zip
        size:

        id: 14403
        name: artworks
        path: /darkstone/extras/darkstone_artworks.zip
        size:
```
