### ISSUE TITLE
problem with democracy_3

### ISSUE THREAD

**Issue by 0-wiz-0** [Sude-/lgogdownloader#85]
I have democracy_3 and all its DLCs. I think since GOG added the newest DLC, lgogdownloader does not correctly work for downloading this game any longer, it dumps core.
It downloads the base game correctly, then the social engineering DLC, then the extremism DLC, but then:
````
gog_democracy_3_extremism_dlc_2.0.0.2.sh
        MD5:    c71614770eaf96613135f2a90a79cef4
        Chunks: 1
        Size:   1331778 bytes

File doesn't exist ./democracy_3/gog_democracy_3_extremism_dlc_2.0.0.2.sh
Downloading: ./democracy_3/gog_democracy_3_extremism_dlc_2.0.0.2.sh
100% ▕██████████████████████████▏ 1.27/1.27MB @ 1.55MB/s ETA: 0s

Repairing file ./democracy_3/setup_democracy3_clones_and_drones_dlc_2.9.0.15.exe
XML: Using remote file
XML: Valid XML
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
[1]   Abort trap (core dumped) lgogdownloader -...
````
Command line used:
````
lgogdownloader --ignore-dlc-count . --save-serials --check-orphans --download --repair --create-xml automatic --no-subdirectories --language all --platform all --game democracy_3
````
democracy_3_africa works fine, as do all other games I tried.

`lgogdownloader --list-details --language all --platform all --ignore-dlc-count .` output for democracy_3:
````
gamename: democracy_3
title: Democracy 3
icon: http://static.gog.com/upload/images/2015/06/2a5f4b0e3f6ad38b960a4ed4d215374e6d31ed91.png
installers: 
        id: en1installer15
        name: Windows Installer, English
        path: /democracy_3/win/english/setup_democracy3_2.13.0.19.exe
        size: 141.4
        updated: True
        language: English

        id: en2installer5
        name: Mac OS Installer, English
        path: /democracy_3/mac/english/democracy_3_2.2.0.47.pkg
        size: 42.6
        updated: True
        language: English

        id: en3installer2
        name: Linux Installer, English
        path: /democracy_3/linux/english/gog_democracy_3_2.1.0.4.sh
        size: 46.4
        updated: True
        language: English

extras: 
        id: 25693
        name: manual
        path: /democracy_3/extras/democracy_3_manual.zip
        size: 

DLCs: 
        gamename: democracy_3_social_engineering
        id: en1installer4
        name: Windows Installer, English
        path: /democracy_3/dlc_social_engineering/win/setup_democracy3_social_engineering_dlc_2.9.0.15.exe
        size: 7.7
        updated: False

        gamename: democracy_3_social_engineering
        id: en2installer2
        name: Mac OS Installer, English
        path: /democracy_3/dlc_social_engineering/mac/dlc_democracy_3_social_engineering_2.1.0.41.pkg
        size: 7.4
        updated: False

        gamename: democracy_3_social_engineering
        id: en3installer1
        name: Linux Installer, English
        path: /democracy_3/dlc_social_engineering/linux/gog_democracy_3_social_engineering_dlc_2.0.0.2.sh
        size: 2
        updated: False

        gamename: democracy_3_extremism
        id: en1installer3
        name: Windows Installer, English
        path: /democracy_3/dlc_extremism/win/setup_democracy3_extremism_dlc_2.9.0.15.exe
        size: 7.5
        updated: False

        gamename: democracy_3_extremism
        id: en2installer2
        name: Mac OS Installer, English
        path: /democracy_3/dlc_extremism/mac/dlc_democracy_3_extremism_2.1.0.41.pkg
        size: 5.7
        updated: False

        gamename: democracy_3_extremism
        id: en3installer1
        name: Linux Installer, English
        path: /democracy_3/dlc_extremism/linux/gog_democracy_3_extremism_dlc_2.0.0.2.sh
        size: 2
        updated: False

        gamename: democracy_3_clones_and_drones
        id: en1installer1
        name: Windows Installer, English
        path: /democracy_3/dlc_clones_and_drones/win/setup_democracy3_clones_and_drones_dlc_2.9.0.15.exe
        size: 8.6
        updated: False

        gamename: democracy_3_clones_and_drones
        id: en2installer2
        name: Mac OS Installer, English
        path: /democracy_3/dlc_clones_and_drones/mac/dlc_democracy_3_clones_and_drones_2.1.0.41.pkg
        size: 7.6
        updated: False

        gamename: democracy_3_clones_and_drones
        id: en3installer1
        name: Linux Installer, English
        path: /democracy_3/dlc_clones_and_drones/linux/gog_democracy_3_clones_and_drones_dlc_2.0.0.2.sh
        size: 3
        updated: False

        gamename: democracy_3_electioneering
        id: en1installer1
        name: Windows Installer, English
        path: /democracy_3/dlc_electioneering/win/setup_democracy3_electioneering_dlc_2.13.0.19.exe
        size: 14.7
        updated: False

        gamename: democracy_3_electioneering
        id: en2installer1
        name: Mac OS Installer, English
        path: /democracy_3/dlc_electioneering/mac/dlc_democracy_3_electioneering_2.2.0.47.pkg
        size: 7.9
        updated: False
````
